name: Frontend CI/CD

on:
  push:
    branches:
      - master
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: Build
        run: |
          cd Frontend
          npm install
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            npm run build -- --mode production
          else
            npm run build -- --mode test
          fi
          
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ github.ref == 'refs/heads/master' && secrets.PROD_SSH_PRIVATE_KEY || secrets.TEST_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ github.ref == 'refs/heads/master' && secrets.PROD_REMOTE_HOST || secrets.TEST_REMOTE_HOST }}
          REMOTE_USER: root
          SOURCE: Frontend/dist/*
          TARGET: ${{ github.ref == 'refs/heads/master' && secrets.PROD_DEPLOY_TARGET || secrets.TEST_DEPLOY_TARGET }}
